export const fileTypes = {
        'exe': 'executable',
        'bat': 'executable',
        'sh': 'executable',
        'bin': 'executable',
        'cmd': 'executable',
        'com': 'executable',
        'doc': 'document',
        'docx': 'document',
        'txt': 'text file',
        'pdf': 'PDF document',
        'jpg': 'image',
        'jpeg': 'image',
        'png': 'image',
        'gif': 'image',
        'mp3': 'audio',
        'wav': 'audio',
        'mp4': 'video',
        'avi': 'video',
        'zip': 'compressed file',
        'rar': 'compressed file',
};
