name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./ftp/server/package-lock.json  # Specify the correct path to package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./ftp/server

      - name: Build the application
        run: npm run build --if-present
        working-directory: ./ftp/server

      - name: Run tests
        run: npm test
        working-directory: ./ftp/server
